#! /bin/sh
# /etc/init.d/hue 

### BEGIN INIT INFO
# Provides:          hue
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting hue"
    # run application you want to start
	cd "__LOCATION__"
	. /root/.nvm/nvm.sh && ./backend.js > /var/log/hue.log 2>/var/log/hue.err
    ;;
  stop)
    echo "Stopping hue"
    # kill application you want to stop
    kill $(ps -ef | grep './backend.js'  | grep -v grep | awk '{print $2}')
    ;;
  *)
    echo "Usage: /etc/init.d/hue {start|stop}"
    exit 1
    ;;
esac

exit 0